Traceback (most recent call last):
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/licensed/anaconda3/2020.11/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x14e726e0ea00>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14e726e0ea00>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/licensed/anaconda3/2020.11/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/licensed/anaconda3/2020.11/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/spacy/__main__.py", line 33, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/plac_core.py", line 367, in call
    cmd, result = parser.consume(arglist)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/plac_core.py", line 232, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/spacy/cli/download.py", line 44, in download
    shortcuts = get_json(about.__shortcuts__, "available shortcuts")
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/spacy/cli/download.py", line 95, in get_json
    r = requests.get(url)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/shortcuts-v2.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14e726e0ea00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/analysis/calculate_baselines.py:75: RuntimeWarning: Mean of empty slice
  mean_sentence = np.nanmean(np.asarray(random_correlations))
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/analysis/calculate_baselines.py:75: RuntimeWarning: Mean of empty slice
  mean_sentence = np.nanmean(np.asarray(random_correlations))
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/analysis/calculate_baselines.py:75: RuntimeWarning: Mean of empty slice
  mean_sentence = np.nanmean(np.asarray(random_correlations))
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/analysis/calculate_baselines.py:75: RuntimeWarning: Mean of empty slice
  mean_sentence = np.nanmean(np.asarray(random_correlations))
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/analysis/calculate_baselines.py:75: RuntimeWarning: Mean of empty slice
  mean_sentence = np.nanmean(np.asarray(random_correlations))
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/scratch/gpfs/mandyl/relative_importance/analysis/calculate_baselines.py:75: RuntimeWarning: Mean of empty slice
  mean_sentence = np.nanmean(np.asarray(random_correlations))
geco
saliency
geco bert
Token alignment errors:  81
Spearman Correlation Model: Mean, Stdev
0.5355734293651041 0.38331429118788746




---------------
Permutation baseline: Mean: 0.00, stdev: 0.04
---------------

geco albert
Token alignment errors:  0
Spearman Correlation Model: Mean, Stdev
0.4805414917785341 0.3990780922059055




---------------
Permutation baseline: Mean: -0.00, stdev: 0.04
---------------

geco distil
Token alignment errors:  81
Spearman Correlation Model: Mean, Stdev
0.5061066584339192 0.3897222961826243




---------------
Permutation baseline: Mean: -0.00, stdev: 0.05
---------------

attention
geco bert
Token alignment errors:  81
Spearman Correlation Model: Mean, Stdev
0.18251484589295297 0.4388215316623401




---------------
Permutation baseline: Mean: -0.00, stdev: 0.05
---------------

geco albert
Token alignment errors:  367
Spearman Correlation Model: Mean, Stdev
0.25550212026464064 0.44057655050114314




---------------
Permutation baseline: Mean: 0.00, stdev: 0.04
---------------

geco distil
Token alignment errors:  81
Spearman Correlation Model: Mean, Stdev
0.06003836713082663 0.4492653781234982




---------------
Permutation baseline: Mean: -0.00, stdev: 0.04
---------------

  importance_type corpus   model  mean_correlation  std_correlation
0        saliency   geco    bert          0.535573         0.383314
1        saliency   geco  albert          0.480541         0.399078
2        saliency   geco  distil          0.506107         0.389722
3       attention   geco    bert          0.182515         0.438822
4       attention   geco  albert          0.255502         0.440577
5       attention   geco  distil          0.060038         0.449265

  importance_type corpus   model  mean_correlation  std_correlation
0        saliency   geco    bert          0.000872         0.044457
1        saliency   geco  albert         -0.000469         0.044478
2        saliency   geco  distil         -0.000305         0.045775
3       attention   geco    bert         -0.000604         0.045301
4       attention   geco  albert          0.001195         0.044779
5       attention   geco  distil         -0.000407         0.044206

Empty DataFrame
Columns: [corpus, baseline_type, mean_correlation, std_correlation]
Index: []

zuco
saliency
zuco bert
Token alignment errors:  71
Spearman Correlation Model: Mean, Stdev
0.6797022212709019 0.2064183065008222




---------------
Permutation baseline: Mean: -0.00, stdev: 0.03
---------------

zuco albert
Token alignment errors:  3
Spearman Correlation Model: Mean, Stdev
0.6192498275115023 0.2260502791054625




---------------
Permutation baseline: Mean: -0.00, stdev: 0.03
---------------

zuco distil
Token alignment errors:  71
Spearman Correlation Model: Mean, Stdev
0.6428957670009539 0.22060635196122058




---------------
Permutation baseline: Mean: -0.00, stdev: 0.03
---------------

attention
zuco bert
Token alignment errors:  71
Spearman Correlation Model: Mean, Stdev
0.11423657134965315 0.3277511337290547




---------------
Permutation baseline: Mean: -0.00, stdev: 0.03
---------------

zuco albert
Token alignment errors:  147
Spearman Correlation Model: Mean, Stdev
0.3689093433689321 0.27783043146453357




---------------
Permutation baseline: Mean: 0.00, stdev: 0.03
---------------

zuco distil
Token alignment errors:  71
Spearman Correlation Model: Mean, Stdev
0.029608780207461088 0.3445260272309567




---------------
Permutation baseline: Mean: -0.00, stdev: 0.03
---------------

   importance_type corpus   model  mean_correlation  std_correlation
0         saliency   geco    bert          0.535573         0.383314
1         saliency   geco  albert          0.480541         0.399078
2         saliency   geco  distil          0.506107         0.389722
3        attention   geco    bert          0.182515         0.438822
4        attention   geco  albert          0.255502         0.440577
5        attention   geco  distil          0.060038         0.449265
6         saliency   zuco    bert          0.679702         0.206418
7         saliency   zuco  albert          0.619250         0.226050
8         saliency   zuco  distil          0.642896         0.220606
9        attention   zuco    bert          0.114237         0.327751
10       attention   zuco  albert          0.368909         0.277830
11       attention   zuco  distil          0.029609         0.344526

   importance_type corpus   model  mean_correlation  std_correlation
0         saliency   geco    bert          0.000872         0.044457
1         saliency   geco  albert         -0.000469         0.044478
2         saliency   geco  distil         -0.000305         0.045775
3        attention   geco    bert         -0.000604         0.045301
4        attention   geco  albert          0.001195         0.044779
5        attention   geco  distil         -0.000407         0.044206
6         saliency   zuco    bert         -0.000504         0.031570
7         saliency   zuco  albert         -0.000045         0.031050
8         saliency   zuco  distil         -0.001223         0.032657
9        attention   zuco    bert         -0.001106         0.033241
10       attention   zuco  albert          0.000102         0.032300
11       attention   zuco  distil         -0.000137         0.031635

Empty DataFrame
Columns: [corpus, baseline_type, mean_correlation, std_correlation]
Index: []

['photographed', 'with', 'melancholy', 'richness', 'and', 'eloquently', 'performed', 'yet', 'also', 'decidedly', 'uncinematic'] [0.12927632 0.04653439 0.14534014 0.08031247 0.0199455  0.11096657
 0.07753867 0.01728019 0.0680929  0.1469141  0.15779875] [1.15382517e-06 4.90490816e-09 7.31640997e-07 5.40729528e-06
 3.88007976e-09 9.28179717e-01 4.85922816e-07 6.78656234e-08
 2.11034781e-08 4.24999858e-07 7.18119816e-02]
Traceback (most recent call last):
  File "analyze_all.py", line 166, in <module>
    visualize_sentence(i, et_tokens, human_importance, lm_importance, "plots/" + model + "_" + str(i) + ".png")
  File "/scratch/gpfs/mandyl/relative_importance/analysis/create_plots.py", line 168, in visualize_sentence
    human_data = pd.DataFrame({"Tokens": tokens, "Importance": human_saliency[i]})
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 64, in arrays_to_mgr
    index = extract_index(arrays)
  File "/scratch/gpfs/mandyl/relative_importance/nlpenv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 365, in extract_index
    raise ValueError("arrays must all be same length")
ValueError: arrays must all be same length
